### ISSUE TITLE
Develop A Plan To Build PolyVent SPI Controller Card Assemblies

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/general-alarm-device#100]
Now that there is a proposed PCB design, Lee proposed we build a few.

Identify the required quantity.  Lee suggests 5.
Choose to have JLCPCB build the SMT components or to build by hand. Lee is willing and suggest we build by hand however we might have more reliable assembly if done by JLCPCB.

We should order long lead parts. This time Lee has identified long lead parts in the BOM.
It is really the through hole three or four connectors and of course the PCB.

If accepted, this effort needs its own milestones.  Perhaps it should even be moved to a project of its own to reduce clutter of the GPAD development.

**Comment by ForrestErickson** [comment]
On 20221115 Lee identifed long lead parts for @RobertLRead 
![image](https://user-images.githubusercontent.com/5836181/204090030-026e20bf-efc8-403d-8ea4-759e7565b791.png)

**Comment by ForrestErickson** [comment]
@RobertLRead ,

Regarding Long Lead Parts Order. Have you placed the order below?
> ![image](https://user-images.githubusercontent.com/5836181/204090407-069fed58-cdc2-49da-89bc-6a51d5d03706.png)

While not yet reviewed, I have updated the PolyVent_SPI_Controller schematic and PCB per the review Lawrence and I had a couple of weeks ago. 
I have added a buck regulator which could more efficiently reduce the 24 volts to 12 volts for output to the GPAD.
> ![image](https://user-images.githubusercontent.com/5836181/204090448-8d82324c-2d73-4fb9-b5d8-67498debfb22.png)


To test this voltage regulation configuration please order an additional item from Amazon: https://www.amazon.com/Zixtec-LM2596-Converter-Module-1-25V-30V/dp/B07VVXF7YX/ref=pd_lpo_2
For $15.98 we get ten of these useful regulators.
> 
![image](https://user-images.githubusercontent.com/5836181/204090348-1bbc5e40-2a4b-4a64-bbfb-a1db693b2c08.png)


Please advise.


FYI,
I hope to have one more review of the PCB and order assemblies from JLCPCB soon.

**Comment by RobertLRead** [comment]
Yes, I just now ordered these. Thanks for documenting them so clearly in this issue.

**Comment by ForrestErickson** [comment]
Hope to have parts in hand in Austin on 12 December. Robert will assemble.
From JLCPCB were ordered 5 raw PCBs and 5 assemblies with SMT.
