### ISSUE TITLE
Button as received from TreatStock orifice is a bit too tight for the square button plunger

### ISSUE THREAD

**Issue by RobertLRead** [PubInv/general-alarm-device#115]
Rob got a 3D printed case from TreatStock. The push button's square hole had to be trimmed down a bit with an X-acto knife for the plunger to fit into tightly.

I suggest that the 3D design must be tweaked to have a larger opening to receive the plunger.

**Comment by ForrestErickson** [comment]
@RobertLRead 
Is this something you can quantify?  I know time has passed it it may be hard to quantify even with out the passage of time. 
From your memory is this something where before and after photographs would have helped us understand?

@LokiMetaSmith 
Is this something you have tweaked already?
