### ISSUE TITLE
Connect DTR on USB to Serial IC to The ATmega328 Reset Through Capacitor Like Arduino Nano Schematic

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/general-alarm-device#116]
This will bring to the GPAD the same program upload of a standard UNO / NANO.

From the Nano Schematic:
![image](https://user-images.githubusercontent.com/5836181/199330888-a102e7d2-1e86-4ebb-ba62-07db67f73679.png)

**Comment by ForrestErickson** [comment]
Reference to CH340 data sheet: https://www.mpja.com/download/35227cpdata.pdf

Our GPAD uses the CH340E in the  MSOP-10 package. This part is the smallest but does not have the DTR pin.
The UNO in Lee's lab uses a CH340G which has the larger SOP-16 package and the DRT pin is on pin 13.

Reading the specification for the CH340 family the CH340G part has some EEPROM into which, for example, a serial number could be stored.  The CH340G is in the larger SOP-16 package only.

**Comment by LokiMetaSmith** [comment]
Confirmed Resolved
