### ISSUE TITLE
Board SN #3 has a broken SPI RJ12 jack pointing upwards....

### ISSUE THREAD

**Issue by RobertLRead** [PubInv/general-alarm-device#118]
Here are the images:

![IMG-3554 (1)](https://user-images.githubusercontent.com/5296671/199342885-0de3fffc-3e9b-45e2-9508-f49815d92dbe.JPG)
![IMG-3555 (1)](https://user-images.githubusercontent.com/5296671/199342899-6444e2b9-670b-43e6-b96a-5cbc11b8367f.JPG)

**Comment by RobertLRead** [comment]
Lee has photos which show this is shipping damage of some kind. (Or, maybe Rob broke when installing in enclosure, although he doubts it.)

**Comment by ForrestErickson** [comment]
Image during Factory Test of #3 (left most of the four). Connector is normal.
![20220928_145843](https://user-images.githubusercontent.com/5836181/199344692-b55eb551-2c32-4cac-bea8-1f0acb9a566b.jpg)

**Comment by ForrestErickson** [comment]
Notes on Lee's shipping to Robert.  Three GPAD PWAs were shipped in one box. Lee does not think it was the same box in which they were received. The three assemblies were individually padded but IIRC for two only with the same padding in which they were received and again IIRE, some alternate and supplemental padding bubble wrap was added.  Lee is rather sure they did not rattle around in the carton / box. 
Robert did not note any damage to the carton / box.

While this may be a one off and this is damage while shipping a unit with out an enclosure, this reminds us that we should identify a card board box and appropriate padding in which to ship an individual unit.

**Comment by ForrestErickson** [comment]
As this is a one off I am closing. I will create an issue to identify a carton and packing in which a single GPAD in an enclosure can be shipped.

**Comment by ForrestErickson** [comment]
Closing as won't fix as we can do nothing further.
