### ISSUE TITLE
GPAD_API Version 0.1 Modifies Text When Echoed, Unexpected or Undocumented Behavior.

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/general-alarm-device#122]
Testing the interface on the serial port of GPAD_API Version 0.1 with the new file GPAD_API_TEST_ALPHANUM1.txt  
* ![image](https://user-images.githubusercontent.com/5836181/199515508-0c30d8de-ac17-4c56-9f12-2ba58c66c5cd.png)

There is Unexpected or Undocumented Behavior to the text traffic on the serial port.

Lee noticed that the DUT echoed back in the terminal window altered strings.  Screen shot of RealTerminal testing:
* ![image](https://user-images.githubusercontent.com/5836181/199515768-2dbf6a00-f61d-44f1-b665-1c6a4d001960.png)

For example the text "a3THE QUICK BROWN FOX JUMPED OVER THE LAZY DOG." was echoed as 

```
I received: 47a3THE QUICK BROWN FOX JUMPED OVER THE LAZY DOG.
                 
Command: a
                                                                    
3
                                                                             
currentlyMuted : 
                                                             
0
                                                                             
interpret Done
                                                                
THE QUICK BROWN FOX 
                                                          
JUMPED OVER THE LAZY
                                                          
 DOG.
 

```
which has additional CRLF inserted.  This mark down document renders the CR and LF into the text displayed just above this note.

Pasting into the RealTerm terminal window (the green text in this screen shot) produces similar results.
* ![image](https://user-images.githubusercontent.com/5836181/199517912-5857ef0f-e7ac-4f3e-88ef-fa456f2fe383.png)

Pasting into the Arduino terminal window produces similar results but with out the helpful indication of CR and LF which RealTerminal provides.
*![image](https://user-images.githubusercontent.com/5836181/199518765-8f708bed-4072-4223-8305-8603d9b87f79.png)

**Comment by ForrestErickson** [comment]
**Caution** on using the file GPAD_API_TEST_ALPHANUM1.txt from the repository. Git changes LF to CRLF and so the file you pull out from the link at: https://github.com/PubInv/general-alarm-device/tree/main/Firmware/GPAD_API_TEST is today 20221102 10:40 AM corrupted.  There is an issue about this corruption.

**Comment by RobertLRead** [comment]
Fixed by GIT configuration.
