### ISSUE TITLE
Add UNO Like Pin Names to Headers, Version 2 PCB

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/general-alarm-device#134]
Will make testing and development easier.

**Comment by LokiMetaSmith** [comment]
This was in the sheet as a note, I would add them to the silk screen, and add an extra net name with them.

**Comment by ForrestErickson** [comment]
20221208 Added text to footprint for UNO3 with and with out mounting holes in General Purpose Alarm Device library.
