### ISSUE TITLE
Identify Selector Switch for nCS, PolyVent_SPI_Controller

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/general-alarm-device#140]
During the discussion of the PolyVent_SPI_Controller PCB it was suggested that we have a rotary selection switch.

Please @LokiMetaSmith , @RobertLRead help identify a desired switch for Lee

**Comment by LokiMetaSmith** [comment]
I think the dip switch is the best option. or jumper pins

I was also thinking of rotary encoders, but I forgot that most of them are binary encoders, and without a demultiplexor it wouldn't work.

![image](https://user-images.githubusercontent.com/5054116/203114763-8c66863c-6dee-4c79-85b7-2f8db1c5695a.png)

https://jlcpcb.com/parts/componentSearch?isSearch=true&searchTxt=binary

https://jlcpcb.com/partdetail/TexasInstruments-CD74HC238PWR/C403724

**Comment by ForrestErickson** [comment]
I have updated the Schematic and PCB with these changes and made a PDF of schematic. Ready for review.
