### ISSUE TITLE
Make Public Invention Logo for SCH and PCB

### ISSUE THREAD

**Issue by RobertLRead** [PubInv/general-alarm-device#15]

**Comment by RobertLRead** [comment]
Lee, here is the Public Invention logo; it is not a professional logo but we have used it for many years:

![logo](https://user-images.githubusercontent.com/5296671/175038579-31bb6e38-6d58-40aa-bcbe-8945232d2776.png)

**Comment by ForrestErickson** [comment]
20220725 made logo and added to PCB.
![image](https://user-images.githubusercontent.com/5836181/180859496-5951f619-8512-4fb9-893a-429b6f3cff69.png)

Note only the text of the logo shows up.

**Comment by ForrestErickson** [comment]
Experiment with the threshold at 70 percent or so.
![image](https://user-images.githubusercontent.com/5836181/180861018-d7443e11-dbdd-4490-afe6-18830f7f9ff6.png)
This preserved the leaves and lighter traces.

**Comment by ForrestErickson** [comment]
Lee would like Robert's opinion on which logo to retain from the above.

**Comment by RobertLRead** [comment]
I like the leaves; but I could be talked out of it!  Back over to you.

**Comment by ForrestErickson** [comment]
If Lee recalls correctly 20220726 Robert agreed to the leafy design which is in the PCB design proposed week ending 20220729.

Let's close this today 20220802.
