### ISSUE TITLE
Add GPL_3 license reference or symbol to SCH and PCB

### ISSUE THREAD

**Issue by RobertLRead** [PubInv/general-alarm-device#16]

**Comment by RobertLRead** [comment]
I recommend that we use the [CERN OHL Version 2 Strongly Reciprocal License for Hardware]:(https://opensource.org/CERN-OHL-S
)
...and use the GPL or the AGPL for code.

**Comment by RobertLRead** [comment]
Dear @ForrestErickson Please add this language to the silkscreen if you can:

CERN Open Hardware License Version 2 - Strongly Reciprocal

**Comment by ForrestErickson** [comment]
Trial placement screen shot.
![image](https://user-images.githubusercontent.com/5836181/181813054-b5fc2155-f23b-4cb9-824e-c62e75e62089.png)

**Comment by LokiMetaSmith** [comment]
The screenshot demonstrates that the correct text,"CERN Open Hardware License Version 2 - Strongly Reciprocal" has been added.
