### ISSUE TITLE
Make GPAD_API ESP32 Compatible

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/general-alarm-device#210]
Probably a development branch is needed with which to do this and in conjunction with students using the GPAD.

The main branch should not be changed / merged if the resulting firmware will not compile and operate with the GPAD ATmega284  processor on the Version 1 and 2 GPAD.

**Comment by LokiMetaSmith** [comment]
I agree, this is a breaking change and will need it's own branch. We can also add in compile time flags for selecting the build version and revision of the PCB, which will make future changes and configurations easier to manage. This would also allow firmware builds to enable or disable features based on the board revision and/or configuration.

**Comment by LokiMetaSmith** [comment]
I've created a new branch and added the pull request contents there.  https://github.com/PubInv/general-alarm-device/tree/esp32_integration
