### ISSUE TITLE
LCD on a machine quit while I was using it...

### ISSUE THREAD

**Issue by RobertLRead** [PubInv/general-alarm-device#222]
I was using SN 3 which was working fine with the LCD showing messages. I was controlling it via SPI from the PolyVent when the LCD went dark, and it has not come back, even after being unplugged and plugged back in.

I did not have it in a case. It was in a precarious position and the back may have shorted against the metal frame of the PolyVent ---or maybe not.

**Comment by ForrestErickson** [comment]
See the troubleshooting notes on #226.

Found and fixed.
