### ISSUE TITLE
general-alarm-device/tree/main/Firmware Links to Lee's Personal Github

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/general-alarm-device#26]
I noticed that the firmware in the GPAD at 
https://github.com/PubInv/general-alarm-device/tree/main/Firmware

is linking to my personal Github at: https://github.com/ForrestErickson/SPI_Controller_And_Peripheral/tree/bde15454bd6f0ddee013070e940d8cc6175c0008

I think this should be changed so that the PubInv repository is fully self contained.
I do not have a strategy to make this change and so that I get smarter, I would like to be advised on how it could and or should be done.

Lee

**Comment by LokiMetaSmith** [comment]
#53 needs to incorporate this code

**Comment by ForrestErickson** [comment]
Lee thinks there is another and worse problem.
The link "https://github.com/ForrestErickson/SPI_Controller_And_Peripheral/tree/bde15454bd6f0ddee013070e940d8cc6175c0008" is to a particular branch or tag and so links to old firmware.

Here is the code to which it links for the Peripheral and with a last update on 24 May 2020 : 
![image](https://user-images.githubusercontent.com/5836181/193934751-10fd839e-8404-4ee3-b47e-a2052d610286.png)

However directly from Lee's repository on Main is this code with an update on 27 September 2022:

![image](https://user-images.githubusercontent.com/5836181/193934904-0ec8c830-c624-476e-ad95-82225e77c164.png)

Lee does not have a mental model of how to fix this. Do I try to do so at the command line.  Will try.

**Comment by ForrestErickson** [comment]
From command line:
![image](https://user-images.githubusercontent.com/5836181/193935382-420dbd89-ef99-4cbe-8bd8-270435579cab.png)


Added the changes in the Firmware folder. Committed. Pushed.
![image](https://user-images.githubusercontent.com/5836181/193935445-742c015c-6282-46d9-8443-e6f78886e3ee.png)

**Comment by ForrestErickson** [comment]
This seams to have done it.
![image](https://user-images.githubusercontent.com/5836181/193935708-618d3087-dac2-4859-9419-16b4afbb3005.png)

**Comment by ForrestErickson** [comment]
Lee would still like to disconnect this from his personal Github repositories to prevent future confusion and to make sure others have access to the code.

**Comment by LokiMetaSmith** [comment]
#84 is related to this issue

**Comment by ForrestErickson** [comment]
Rob has plan and will make this happen.

**Comment by RobertLRead** [comment]
This connection has now been removed. I copied Lee's code (almost unchanged) for SPI reception into the main GPAD_API routine. I copied his "controller" code into a new sketch : GPAD_API_SPI_CONTROLLER.ino .

I have tested these, and they work as intended. That is, the a button press on a GPAD board with the controller code loaded is read on the peripheral board (which is also a GPAD) and can be output with debugging statements and can control a light.

As requested in this issue I have permanently removed the link to Lee's personal github, as now somewhat superfluous and potentially confusing. I will create a new issue for the improvement of this test to transfer real alarm information and messages (which will require improvements in the peripheral to interpret.)

**Comment by ForrestErickson** [comment]
@RobertLRead 

Regarding, "... removed the link to Lee's personal github"
Thanks.
I may not be remembering correctly but I think when I was adding the code into the Public Invention repository the GIT CLI may have asked me a question something like is this to be included as a subproject. The result of my answer, what ever it was, was this goofy connection.
