### ISSUE TITLE
Enclosure Design

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/general-alarm-device#29]
Kincheloe, Lawrence
SPECT

I found this project for designing and 3D printing parametrically defined project boxes. 
https://hackaday.com/2018/03/02/printed-it-custom-enclosure-generator/
https://www.thingiverse.com/thing:1264391/files

It looks comprehensive and perfect for our application.

**Comment by ForrestErickson** [comment]
20220712 discussion around enclosure. By moving LEDs from under the LCD to the right of  room can be made for fitting in the USB connector and circuits bringing all  connections to the bottom edge.

**Comment by LokiMetaSmith** [comment]
I pushed a folder in the Hardware directory for the Enclosure, that contains the latest STEP 3D export of the PCB and an initial mock-up of the enclosure, as well as a thrown together FreeCAD file that imports both in a single view.

**Comment by LokiMetaSmith** [comment]
Hum,. I somehow obliterated everything I was working on over the weekend and today. Not sure how that happened. I'll have to re-build what I was working on for the enclosure.

**Comment by LokiMetaSmith** [comment]
https://medium.com/@livnoorbrar/lost-code-by-accidentally-creating-a-detached-head-dont-worry-58919f32b08d

This saved my butt. It should be safely committed now.

**Comment by LokiMetaSmith** [comment]
Add mounting tabs to the enclosure, per discussion with Lee

**Comment by ForrestErickson** [comment]
I have created a mechanical placement drawing for (I hope) all of the components that penetrate the enclosure. 
For the LCD I have dimensioned to the center. It is not very obvious.
For the UNO footprint I have dimensioned to the pin 1 and none of the other features.

The file is at: https://github.com/PubInv/general-alarm-device/blob/main/Hardware/GeneralPurposeAlarmDevicePCB/GeneralPurposeAlarmDevicePCB/MechanicalPartsPlacement.pdf

**Comment by ForrestErickson** [comment]
Added drawings to parts folder for potentiometer and for JST-MFG connector.

**Comment by LokiMetaSmith** [comment]
This is taking longer than expect, work is going well. Translating the origin coordinates was non-obvious at first.

**Comment by LokiMetaSmith** [comment]
![image](https://user-images.githubusercontent.com/5054116/185857545-f279c9df-b8bb-4225-8fa6-18283fcbe4e3.png)

coming together

**Comment by ForrestErickson** [comment]
As of 20221025 Robert has received a prototype enclosure from TreatStock and will report on fit next week. Including how well the screws drive.
Photos when possible.

**Comment by RobertLRead** [comment]
This enclosure is accepted as a workable design at present, so we are closing this issue.
