### ISSUE TITLE
Understanding Tagging on Git and Github

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/general-alarm-device#33]
With out fear of contraction Lee can say he does not understand tagging work flow on git CLI and Github web interface.

![image](https://user-images.githubusercontent.com/5836181/180623521-5d623760-7242-4e99-bbd0-a3f6f0a645c8.png)

I wanted a tag before I began a tear up of PCB traces and made the above local tag and pushed it.

I see no new tag on the web interface as I expected I would.

![image](https://user-images.githubusercontent.com/5836181/180623553-db1499e0-749a-45fb-b1e4-2cd7fb8e35fe.png)

**Comment by LokiMetaSmith** [comment]
Sharing Tags
By default, the git push command doesn’t transfer tags to remote servers. You will have to explicitly push tags to a shared server after you have created them. This process is just like sharing remote branches — you can run git push origin <tagname>.

So following the above, you must simply type:
git push origin VersionZeroPCB 



From: https://git-scm.com/book/en/v2/Git-Basics-Tagging#:~:text=Sharing%20Tags&text=git%20push%20%2D%2Dtags,be%20pushed%20to%20the%20remote.

**Comment by ForrestErickson** [comment]
Thanks for the reminder. 

It worked:
![image](https://user-images.githubusercontent.com/5836181/180660812-08b97e20-b243-4a1a-8bc9-e8720b5b8391.png)

**Comment by ForrestErickson** [comment]
Lee thinks he can find these notes on Tagging the next time needed. That time will be when we place the order for Version 1 PCBs as we will want to be able to refer to this hardware build event.

Let's close this today 20220802.
