### ISSUE TITLE
As a user in a Low and Middle Income Country (LMIC), I need GPAD to cost less than $100USD.

### ISSUE THREAD

**Issue by LokiMetaSmith** [PubInv/general-alarm-device#41]

**Comment by LokiMetaSmith** [comment]
This requires an estimated BOM to be generated

**Comment by ForrestErickson** [comment]
Lee has generated a costed BOM. See file: https://github.com/PubInv/general-alarm-device/blob/main/Hardware/GeneralPurposeAlarmDevicePCB/GeneralPurposeAlarmDevicePCB/GeneralPurposeAlarmDevicePCB.xls

The KiCad BOM CSV file is opened and pasted into a tab in this spread sheet which has another tab to process for cost estimation. There is an instruction tab too.
 
There are three components for which no price is known. The PCB and assembly cost, the enclosure, and a TBD Arduino shield for applications TBD.  Lee entered the cost for these three items as $1,000,000 to call attention to them.
Also not captured or flagged, is cost to test nor any packing material.

The resulting cost is $3,000,0027.28.
Screen shot:
![image](https://user-images.githubusercontent.com/5836181/182373604-32abf122-d263-4585-9594-b8715b865f93.png)

**Comment by ForrestErickson** [comment]
We need estimates for PCB and assembly. Assuming this will come as we generate a purchase from JLCPCB.
We need an estimate for the enclosure.
Lee thinks we can set the hypothetical Arduino UNO shild cost to zero for now.
Do we want to add in estimates for test (including loading firmware)?
Do we want to add in estimates for packaging?

All of this is reoccurring costs. No estimates for one time costs. No one time costs (such as test for FCC Part 15 EMC) are identified as required.

**Comment by LokiMetaSmith** [comment]
Assembly estimated to be $15/hr and maybe 15-30 minutes to test, assemble and verify.
the enclosure can be estimated (when it is complete) with Shapeways.com, or pcbyway's 3D printing service. It is estimated that the cost of  the enclosure will be below $15

Also, the arduino is for development purposes and won't be included in the final BOM
