### ISSUE TITLE
Make 3D Body for JST Connector at J105

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/general-alarm-device#44]
Lee has made a PCB footprint but has not made a 3D foot print. 

Lawrence, Suggestions?  

PCB screen shot.
![image](https://user-images.githubusercontent.com/5836181/181586228-8d537401-a51f-46f9-8b4a-e2a7f9c3a9d6.png)
Connector screen shot.
![image](https://user-images.githubusercontent.com/5836181/181586394-1ec5c3fb-324e-4e02-8acd-77376aecfbdb.png)

Connector data sheet:
https://datasheet.lcsc.com/lcsc/1811011927_JST-Sales-America-S04B-XASK-1-LF-SN_C265097.pdf

**Comment by LokiMetaSmith** [comment]
No CAD looks available, recommend square 3D block to represent the connector

**Comment by ForrestErickson** [comment]
Updates PCB and Pretty files committed with simple rectangle made in FreeCAD for 3D model.

@LokiMetaSmith Could you update your PCB and try the fit into the enclosure to check for the JST connector. Note the latch on the jack to which the plug engages is not modeled.

**Comment by ForrestErickson** [comment]
Top view
![image](https://user-images.githubusercontent.com/5836181/201524453-5e34a40e-829c-466b-81ce-d30d2560f404.png)


![image](https://user-images.githubusercontent.com/5836181/201524418-43cea895-a105-4c3b-80a8-67adc080f061.png)
