### ISSUE TITLE
20x4 LCD Footprint Error (Warning)

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/general-alarm-device#46]
While it should be a warning, KiCad is set up to return an error it has found in the LCD footprint .

![image](https://user-images.githubusercontent.com/5836181/181861499-05bce5e0-b69a-4ce7-bc26-4bb61fb3f0df.png)

This is a detail of the court yard was was inherited from the PCB footprint (which I got I know not where any more).
Perhaps I made it from a 20x2 LCD. I did not draw this feature.

While I can and will short term, set to ignore this error I will try to find time to understand the root cause and modify the foot print to clear it in the future.

**Comment by LokiMetaSmith** [comment]
This issue isn't showing up when I run DRC.

**Comment by ForrestErickson** [comment]
Regarding, "This issue isn't showing up when I run DRC."

I have probably added it to the exclusion list. 

The delete all markers check box may bring up a dialog for finer grain clearing of DRC exclusions.  I do remember once being confused about it all and unable to get back to errors I know I had excluded. I attributed it to my old brain not remembering how to find the dialog but perhaps there is a bug.

**Comment by ForrestErickson** [comment]
Notes on clearing this error.
I made a new simple project. I selected an UNO shield template and called the project KiCadLibrary. 
![image](https://user-images.githubusercontent.com/5836181/201533685-b7d28dd7-02c0-45ff-b399-f5c7f6b61980.png)
Using the Symbol and Footprint library managers, I then connected the new project to the libraries in the GPAD folder.

![image](https://user-images.githubusercontent.com/5836181/201533748-92aafbb6-e334-4823-b529-061a132a7cf0.png)
![image](https://user-images.githubusercontent.com/5836181/201533807-3f42b11a-4fcb-4d62-8981-ada556222608.png)

I added the LCD to the schematic and annotated it.
I imported new parts into the PCB.
I ran the DRC and reproduced the errors related to the LCD. Courtyard not closed and self intersecting.
![image](https://user-images.githubusercontent.com/5836181/201533916-33f1dd75-b4bb-436b-a13e-c2425e31b921.png)

I right clicked to edit the footprint and turned off all but the front courtyard layer.
![image](https://user-images.githubusercontent.com/5836181/201534044-f4d63d95-6613-4e57-aa1e-fecbf6c47b53.png)

I selected the suspect lines and moved to the front silk screen layer.
![image](https://user-images.githubusercontent.com/5836181/201534098-caefe46f-7e38-496b-ad0b-2b57a9b06a77.png)
Saved the change and reran DRC.

This cleared the errors.
![image](https://user-images.githubusercontent.com/5836181/201534165-89a99432-37c9-45e7-ad5d-47fa0e4bdf51.png)

**Comment by ForrestErickson** [comment]
The work above was only on the local PCB copy of the foot print. So reopened the footprint editor and used Saved As to save into the GPAD library.

![image](https://user-images.githubusercontent.com/5836181/201534259-e230efb1-9cf6-426a-8fd4-6a75131be29f.png)

And selected to overwrite.
![image](https://user-images.githubusercontent.com/5836181/201534318-5833fd2e-e563-4620-bd01-d826d3bb45a3.png)

I added a second LCD to the schematic and updated the PCB to bring it it. I reran DRC and there were no errors for the second LCD.

**Comment by ForrestErickson** [comment]
I think this clears this issue with the LCD module. 
The interfering mounting holes remain to fix.

**Comment by ForrestErickson** [comment]
Note on LCD mounting holes. The LCD measures 0.133 inch diameter or 3.37 mm.
The pad property on the Version 1 PCB footprint is only 2.5mm
![image](https://user-images.githubusercontent.com/5836181/201542760-aeadb802-d88f-46c7-bb42-37139d632c0d.png)

Change to:
![image](https://user-images.githubusercontent.com/5836181/201542912-7eac844e-60c5-44c1-9f4f-91acca41a5c3.png)

Make holes through hole plated and ground. Add to PCB.
![image](https://user-images.githubusercontent.com/5836181/201544125-e425eb00-1079-43f3-a6ce-95d7f61e3dba.png)
