### ISSUE TITLE
Order RJ12 Data Cables for GPAD Version 1 Build

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/general-alarm-device#49]
Quantity 15?

Ship to Lawrence.

**Comment by LokiMetaSmith** [comment]
This is acceptable

**Comment by ForrestErickson** [comment]
Note RJ12 breakout adapters:
https://www.amazon.com/Electronics-Salon-Right-Breakout-Terminal-Connector/dp/B01GNO4L6K

RJ12 Data Cables, 
https://www.amazon.com/NECABLES-Cable-Phone-Straight-Wired/dp/B09NVHF89C/ref=sr_1_1_sspa?th=1

**Comment by RobertLRead** [comment]
@LokiMetaSmith can you email me your shipping address privately? <read.robert@gmail.com>

**Comment by LokiMetaSmith** [comment]
This needs to be added to the Digikey order

**Comment by ForrestErickson** [comment]
We will need only to order in advance of when students start working with GPAD. Lawrence, Lee and Robert each have at least one at this time.
