### ISSUE TITLE
Add note to Schematic for Versions 1 Regarding PCB SMT Footprints Are Set for Hand Solder

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/general-alarm-device#51]
Add a note to the schematic documenting that the Version 1 PCB was generated with "hand soldered" footprints for SMT capacitors and resistors.  This PCB is marked, "Prototype#1, 20220726"

Future "us" or future other users of this project may want the standard SMT footprints  and should generate a distinct PCB with a distinguishable file name (part number).

**Comment by LokiMetaSmith** [comment]
This board has been designed with smt footprints for capacitors and resistors.
