### ISSUE TITLE
Integrate the two simulation files that we have to create an initial version of firmware.

### ISSUE THREAD

**Issue by RobertLRead** [PubInv/general-alarm-device#53]
One of the files is: [https://github.com/PubInv/general-alarm-device/tree/main/simulation/robSimulatinSat13](https://github.com/PubInv/general-alarm-device/tree/main/simulation/robSimulatinSat13)

**Comment by LokiMetaSmith** [comment]
#26 needs to incorporate this into the integration as well.

**Comment by ForrestErickson** [comment]
Lee has experimented some more with Wokwi.
I have simulated making tones and learned that I was mistaken about simultaneous tones. The Arduino tone() command can only work on one pin at a time. (I am assuming I once saw a DTMF project that made tones another way which lead me to my mistaken conclusion.)

However, with the hardware as implemented in Version #1 PCB we can set a **Tone** pin and we can assert an **Attenuate** pin low impedance OUTPUT to reduce the volume of the **Tone**.   Please note another constraint, that when setting the Tone pin that **Light0** pin cannot be a PWM (Cannot use Analogwrite on Light0 pin).  See https://www.arduino.cc/reference/en/language/functions/advanced-io/tone/
_Use of the tone() function will interfere with PWM output on pins 3 and 11 (on boards other than the Mega)._

Here is a Wokwi simulation file Lee made to exercise the tone and attenuation. 
https://wokwi.com/projects/338616554801332819
![image](https://user-images.githubusercontent.com/5836181/184979605-b3a9a914-72b1-4199-b0e8-7776cb97937e.png)

**Comment by ForrestErickson** [comment]
In issue #90 we have found we can create Wokwi specific code.
This is closed.
