### ISSUE TITLE
I2C Address of LCD set for 0x30 (A2, A1, and A0 Low).  Version 1 Build.

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/general-alarm-device#57]
Just FYI.

Referring to the schematic page 4 of 6, the typical default I2C peripheral address of LCD is set for the PCF8574 with A2, A1, and A0 high.  This would correspond to resistors on our aboard R305, R307 and R309 not stuffed (aka DNI).  However in the schematic I put in a value of 1Ohm so when built to our parts list  in the August 2022 build event, the address will be a different address than the default likely to be found in example code all over the internet.  The exact address can be figured out from the PCF8574 data sheet.

Their is no hardware reason to prefer one address over another.

This specific hardware configuration simply needs be noted for firmware development.

**Comment by ForrestErickson** [comment]
Data sheet to be found at: https://www.nxp.com/docs/en/data-sheet/PCF8574_PCF8574A.pdf

Page 5 explains the address decoding.
![image](https://user-images.githubusercontent.com/5836181/184983779-996b6174-6a70-4b4c-9215-de5508d9a846.png)

Our schematic (BOM) calls out the PCF8574A.
So, If I read this correctly, the slave address will be 0x70 to write to the display.

**Comment by ForrestErickson** [comment]
A good article, reference, for programing LCD features found here: 
https://lastminuteengineers.com/i2c-lcd-arduino-tutorial/

Note that customer characters can be created.
What custom characters might be of use for PolyVent?

Consider graphical like combinations of multiple characters too.

**Comment by LokiMetaSmith** [comment]
i2c 0x38 has been tested to work with v1 of the board

**Comment by LokiMetaSmith** [comment]
Change has been made to the GPAD test firmware
