### ISSUE TITLE
Create GPAD Factory Test Firmware

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/general-alarm-device#58]
Factory test requires firmware that exercises the features to allow for quick determination of feature functions.

**Comment by ForrestErickson** [comment]
Lee has committed firmware: https://github.com/PubInv/general-alarm-device/tree/main/Firmware/GPAD_Factory_Test
It was simulated on Wokwi at:  https://wokwi.com/projects/340248560782017108

Press the button to light the five LEDs and make tone.
![image](https://user-images.githubusercontent.com/5836181/185195287-a8f6c036-c286-49d0-baae-7eef5e5fdd0e.png)

**Comment by ForrestErickson** [comment]
As of 20220817 1200, this test does not cover the SPI Peripheral interface.
This test assumes the Arduino UNO boot loader is installed by a method TBD.

**Comment by ForrestErickson** [comment]
As of 20220817 1200, this test does not cover independently test the LIGHT0-LIGHT4. A "walking one" test would be better.

**Comment by LokiMetaSmith** [comment]
Task List:
- [ ] Add a function that will light in succession LIGHT 0 through LIGHT 4
- [ ] Add display text to describe the current test action and expected result
- [ ] Add a test function to verify SPI functionality
- [ ] Add a test function to verify i2c  functionality
- [ ] For i2c test for the ACK bit when testing the display function
- [ ] Exercise the display by showing all 20x4 characters as black squares
- [ ] Exercise the character table by walking through each one

**Comment by ForrestErickson** [comment]
Note the Wokwi documentation located at:
https://docs.wokwi.com/parts/wokwi-lcd1602

indicated we can set an I2C address attribute for the simulation.

![image](https://user-images.githubusercontent.com/5836181/189958346-c93c3da3-3762-47d1-8596-12704fe3a7e3.png)

 The simulation should be updated for the address Lawrence found to work.

**Comment by ForrestErickson** [comment]
Here is code with the Lawrence change.
![image](https://user-images.githubusercontent.com/5836181/189958976-d053ca11-e36e-4b3c-85d4-0ae4869338cc.png)

**Comment by ForrestErickson** [comment]
Lee has updated the I2C address of the display in the simulation at: https://wokwi.com/projects/340248560782017108

It now works on address 0x38 as does the hardware.

![image](https://user-images.githubusercontent.com/5836181/189961348-221c5ee4-9410-4e35-8197-1b922fe4e083.png)

**Comment by ForrestErickson** [comment]
Updated factory test firmware 20220922 for the buzzer at 4KHz and it is much louder. Unpleasant too.

**Comment by ForrestErickson** [comment]
Detail on: Add a test function to verify i2c functionality

Make a conditional test that the exact address for the LCD is found during the I2C scan and if not warn the tester with a Serial.println() message.

**Comment by RobertLRead** [comment]
This code has been reviewed and works well. New features may be requested with issues.
