### ISSUE TITLE
Links To Images of Display PCB Assembly Broken on Main Readme.md

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/general-alarm-device#59]
On 20220820 Lee found the main readme.md at

https://github.com/PubInv/general-alarm-device

has no images ofr the PCB Assembly front and rear.
![image](https://user-images.githubusercontent.com/5836181/185768003-c3bd897a-5846-401d-b7f9-2a666b556b51.png)

I am using my Windows 7 lap top with FireFox browser.

**Comment by ForrestErickson** [comment]
Lee thinks he found the images in a new location at: \general-alarm-device\Hardware\Documentation\PICS

**Comment by ForrestErickson** [comment]
Looks like history shows images moved.  My local git log also shows history of a "conflict" with some of the files in the hardware folder and Lee is not sure of the significance of this log message. 
I assume no action is needed it is just history of a conflict which is now resolved.

![image](https://user-images.githubusercontent.com/5836181/185768792-78e1a4a9-1c15-4d73-85ee-a3f09152aca4.png)

**Comment by LokiMetaSmith** [comment]
Fixed this when I updated the latest enclosure rendering
