### ISSUE TITLE
Create Manufacturing and Unit Test Documentation

### ISSUE THREAD

**Issue by LokiMetaSmith** [PubInv/general-alarm-device#61]
Document manufacturing processes and in field testing of the device

We'll need to make sure the following are avaialble

- [ ] Updated schematic pdf
- [ ] Updated BOM files from all vendors used
- [ ] Notes on what worked and didn't work in terms of tools, parts and selected manufactrers
- [ ] Tools need to assemble/disassemble the unit
- [ ] Update the markdown documentation files to link correctly to each section and subsection of relevant documents

**Comment by ForrestErickson** [comment]
20220922 Lee started this document. 
https://github.com/PubInv/general-alarm-device/blob/main/Hardware/Documentation/ManufacturingUnitTestTroubleshooting.md

**Comment by ForrestErickson** [comment]
Further changes will be by issues as approrpate.
