### ISSUE TITLE
Will Enclosure Benifit From Thread-Rolling-Plastic-Finish-Phillips Scews?

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/general-alarm-device#62]
Will our enclosure benefit from designing screw pockets to receive this kind of screw?

https://www.amazon.com/Thread-Rolling-Plastic-Finish-Phillips/dp/B00GDYDCC0/ref=asc_df_B00GDYDCC0
Drawing: https://m.media-amazon.com/images/I/61OymjyafhL.pdf

What is the appropriate hole size (tread engagement) by material type?  Lee found no design information on the Amazon drawing.

**Comment by ForrestErickson** [comment]
Lee found a very long article about screws into plastics:
https://www.stanleyengineeredfastening.com/-/media/web/sef/resources/docs/other/threaded_fasteners_for_plastics.ashx

**Comment by ForrestErickson** [comment]
Lee spoke with a former coworker who designs plastic injection molded enclosures and he told me of a part you heat in the tip of a soldering iron and then press into 3D printed parts to get metal threads in parts.

https://www.mcmaster.com/threaded-inserts/for-use-in~plastic/heat-set-inserts-for-plastic-7/
![image](https://user-images.githubusercontent.com/5836181/186493228-1482e05a-7782-4859-8aef-3cf0ed8301ac.png)

**Comment by LokiMetaSmith** [comment]
We'll try sheet metal screws and evaluate their effectiveness.

**Comment by RobertLRead** [comment]
We believe plain "#2" screws and also M2 screws will work.
