### ISSUE TITLE
wrong mounting hole screw diameter in footprint LCD_2004A

### ISSUE THREAD

**Issue by LokiMetaSmith** [PubInv/general-alarm-device#65]
Library footprint LCD_2004A has the wrong mount hole size, 

Listed mounting screw diameter 2.5mm
Actual diameter of a 4-40 screw 2.845 mm
Recommended hole size should be 3mm

**Comment by LokiMetaSmith** [comment]
We should push this change up to the root open source library.
I belive it is at https://github.com/KiCad/kicad-library

**Comment by ForrestErickson** [comment]
Add additional relief around mounting holes so that a 4-40 mounting nut does not ground the display unintentionally. 
The mounting holes should be such that then can be grounded intentionally.

**Comment by LokiMetaSmith** [comment]
confirmed resolved

**Comment by ForrestErickson** [comment]
The Rev 2 PCB assembled nicely.
