### ISSUE TITLE
Add relevant prototype ordered parts to BOM   

### ISSUE THREAD

**Issue by LokiMetaSmith** [PubInv/general-alarm-device#68]
Parts ordered from Amazon, digikey, mouser, and other sources need to be added to the BOM

**Comment by LokiMetaSmith** [comment]
Also capture labor effort and estimated assembly cost associated with the board. 
Places this can be found are JLCPCB assembly fee, and estimated time to assemble.

**Comment by ForrestErickson** [comment]
@LokiMetaSmith 
Do you have a list of BOM updates on which Lee can work to check the part numbers in the schematic?

CC: @RobertLRead

**Comment by LokiMetaSmith** [comment]
general-alarm-device\Hardware\Manufacturing has a list of all parts ordered from digikey , LCSC and jlcpcb
