### ISSUE TITLE
D105 Polarity Backwards, Version 1 PCB

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/general-alarm-device#75]
Diode D105 does not light on Version 1 build. 
Polarity of PCB foot is opposite of schematic symbol.
Work around, mount with opposite indicated polarity of the silk screen.

Need to fix for Version 2.
Fix by rotating the connections so that the flat will be "inboard" on the PCB just as Version 1 PCB.

**Comment by ForrestErickson** [comment]
@LokiMetaSmith FYI this was an Issue about which I forgot to tell you. Please rework the GPADs you have assembled.

**Comment by ForrestErickson** [comment]
Fixed in schematic and propagated to PCB. I copied the LED schematic symbol from the D201 location.

**Comment by LokiMetaSmith** [comment]
Confirmed Resolved
