### ISSUE TITLE
J101 footprint mechanical size

### ISSUE THREAD

**Issue by LokiMetaSmith** [PubInv/general-alarm-device#79]
Tolerance on the mechanical retention holes on the footprint are too large and leaves a lot of room for movement.

**Comment by ForrestErickson** [comment]
From drawing here are footprint dimensions.  

![image](https://user-images.githubusercontent.com/5836181/201537576-a399b036-83d2-4feb-8fcc-c3e2527c7e06.png)

Hole size in PCB one of two.
![image](https://user-images.githubusercontent.com/5836181/201537677-000e0648-4b92-4416-b301-db8a178fd222.png)

Update hole size two of two.
![image](https://user-images.githubusercontent.com/5836181/201537777-77e9960c-b549-4bc7-af4b-a02e25d80086.png)

**Comment by ForrestErickson** [comment]
Save changes into the GPAD library and overwrite.
![image](https://user-images.githubusercontent.com/5836181/201537823-6de19ef9-e652-4872-9850-492c7146947d.png)

**Comment by LokiMetaSmith** [comment]
Confirmed Resolved
