### ISSUE TITLE
Bow PCB, on Version 1.  Speculate on Tweaking Out on Serial Numbers 7-15.

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/general-alarm-device#81]
For the Version 1 PCB from JLCPCB, Lawrence found a slight bowing to the PWA.
Lee found for a raw PCB with a straight edge and feeler gauge that that 0.010 would not fit but 0.008" would.

![image](https://user-images.githubusercontent.com/5836181/193892680-d17aacb5-2bae-4242-ad1f-9cd0cedc4a31.png)

Lee would think this is natural given the unequal copper on the top and bottom of the PCB and may be entirely batch to batch dependent and may be negligible.

However, for Version 1, PWAs, Serial Numbers 7-15, we might try to hold flat the GPAD PCB when soldering the LCD module at the 16 pin connector to

**Comment by LokiMetaSmith** [comment]
This issue can be closed when added to the documentaion

**Comment by RobertLRead** [comment]
We agree.
