### ISSUE TITLE
Add manufacturing documentation for jumper based bootloader upload

### ISSUE THREAD

**Issue by LokiMetaSmith** [PubInv/general-alarm-device#83]
There is another way to flash the bootloader using just jumpers. Needs a picture showing the process, a description of the process and a link to the related article describing how it's done.

**Comment by ForrestErickson** [comment]
@LokiMetaSmith 

Please see: https://github.com/PubInv/general-alarm-device/blob/main/Hardware/Documentation/ManufacturingUnitTestTroubleshooting.md

Look for the section begining with: 
> Load Firmware
Load Bootloader
Use an Arduino UNO as an ISP (Incircuit Serial Programmer) which will load the boot loader into the DUT. Cable Connect the ISP UNO to the DUT as follows:

Is that documentation adequate?
For example, do you think your RAs could follow this?

Please advise.
Lee
