### ISSUE TITLE
Expand serial interface to support messages for testing.

### ISSUE THREAD

**Issue by RobertLRead** [PubInv/general-alarm-device#97]
Right now we have the simplest possible serial language, we enter "a3" to assert alarm level 3 for example. I intend to expand this a single line like "a3Patient disconnect detected\n". 

This is not a particularly attractive way to do this, I think JSON would be better, as I have done on other projects. However, it is good enough for testing. We may someday define the actual alarm protocol as a versioned protocol (this would be a good task for an RA).

**Comment by RobertLRead** [comment]
This is done. Since we are not yet implementing official code review and QA, I'm closing this without permission from @ForrestErickson and @LokiMetaSmith .

**Comment by ForrestErickson** [comment]
I am going to suggest a coding method using the Serial Event style as per this example
https://docs.arduino.cc/built-in-examples/communication/SerialEvent

This method confines to the serial event (interrupt) to accumulating the characters till a delimiter is reached and leaves to the main loop the further processing only of the full buffer.

FYI I have never tried to devise a test to break the case where reading is done in the main loop and assume with the very small payload of the commands it would be very unlikely to break the system.
